import { Nunito } from 'next/font/google'
import '@/styles/tailwind.css'
import Container from '@/components/Container'
import Header from '@/components/Header'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={nunito.className}>
				<Container>
					<div className="py-7">
						<Header />

						{children}
					</div>
				</Container>
			</body>
		</html>
	)
}
